const list = [
  {
    group: 0,
    cnName: "语音通话",
    enName: "Voice Call",
    description: "Android SDK API",
    product: "Voice",
    platform: "Android",
    category: "java",
    url: "index.html",
    iconfont: "&#xe62b;",
  },
  {
    group: 17,
    cnName: "控制台 RESTful API",
    enName: "Console RESTful API",
    description: "RESTful API",
    product: "Agora Platform",
    platform: "RESTful",
    category: "swagger",
    url: "rtc/restfulapi",
    iconfont: "&#xe62b;",
  },
  {
    group: 0,
    cnName: "语音通话",
    enName: "Voice Call",
    description: "iOS SDK API",
    product: "Voice",
    platform: "iOS",
    category: "oc",
    url: "docs/headers/Agora-Objective-C-API-Overview.html",
    iconfont: "&#xe62b;",
  },
  {
    group: 0,
    cnName: "语音通话",
    enName: "Voice Call",
    description: "macOS SDK API",
    product: "Voice",
    platform: "macOS",
    category: "oc",
    url: "docs/headers/Agora-Objective-C-API-Overview.html",
    iconfont: "&#xe62b;",
  },
  {
    group: 0,
    cnName: "语音通话",
    enName: "Voice Call",
    description: "C++ API for All Platforms",
    product: "Voice",
    platform: "Windows",
    category: "cpp",
    url: "index.html",
    iconfont: "&#xe62b;",
  },
  {
    group: 0,
    cnName: "语音通话",
    enName: "Voice Call",
    description: "Web SDK API (3.x)",
    product: "Voice",
    platform: "Web",
    category: "web",
    url: "index.html",
    iconfont: "&#xe62b;",
  },
  {
    group: 0,
    cnName: "语音通话",
    enName: "Voice Call",
    description: "Web SDK API (4.x)",
    product: "Voice",
    platform: "Web",
    category: "web_ng",
    url: "index.html",
    iconfont: "&#xe62b;",
  },
  {
    group: 0,
    cnName: "语音通话",
    enName: "Voice Call",
    description: "小程序 SDK API",
    product: "Voice",
    platform: "微信小程序",
    category: "wechat",
    url: "index.html",
    iconfont: "&#xe62b;",
    lang: ["cn"],
  },
  {
    group: 0,
    cnName: "语音通话",
    enName: "Voice Call",
    description: "Electron SDK API",
    product: "Voice",
    platform: "Electron",
    category: "electron",
    url: "index.html",
    iconfont: "&#xe62b;",
  },
  {
    group: 0,
    cnName: "语音通话",
    enName: "Voice Call",
    description: "Unity SDK API",
    product: "Voice",
    platform: "Unity",
    category: "unity",
    url: "index.html",
    iconfont: "&#xe62b;",
  },
  {
    group: 0,
    cnName: "语音通话",
    enName: "Voice Call",
    description: "React Native SDK API",
    product: "Voice",
    platform: "React Native",
    category: "react_native",
    url: "index.html",
    iconfont: "&#xe62b;",
  },
  {
    group: 0,
    cnName: "语音通话",
    enName: "Voice Call",
    description: "Flutter SDK API",
    product: "Voice",
    platform: "Flutter",
    category: "flutter",
    url: "index.html",
    iconfont: "&#xe62b;",
  },
  {
    group: 0,
    cnName: "语音通话",
    enName: "Voice Call",
    description: "Cocos Creator SDK API",
    product: "Voice",
    platform: "Cocos Creator",
    category: "cocos_creator",
    url: "index.html",
    iconfont: "&#xe62b;",
  },
  {
    group: 0,
    cnName: "语音通话",
    enName: "Voice Call",
    description: "Cocos2d-x SDK API",
    product: "Voice",
    platform: "Cocos2d-x",
    category: "cpp",
    url: "index.html",
    iconfont: "&#xe62b;",
  },
  {
    group: 0,
    cnName: "语音通话",
    enName: "Voice Call",
    description: "RESTful API",
    product: "Voice",
    platform: "RESTful",
    category: "swagger",
    url: "rtc/restfulapi",
    iconfont: "&#xe62b;",
  },
  {
    group: 1,
    cnName: "视频通话",
    enName: "Video Call",
    description: "Android SDK API",
    product: "Video",
    platform: "Android",
    category: "java",
    url: "index.html",
    iconfont: "&#xe62d;",
  },
  {
    group: 1,
    cnName: "视频通话",
    enName: "Video Call",
    description: "iOS SDK API",
    product: "Video",
    platform: "iOS",
    category: "oc",
    url: "docs/headers/Agora-Objective-C-API-Overview.html",
    iconfont: "&#xe62d;",
  },
  {
    group: 1,
    cnName: "视频通话",
    enName: "Video Call",
    description: "macOS SDK API",
    product: "Video",
    platform: "macOS",
    category: "oc",
    url: "docs/headers/Agora-Objective-C-API-Overview.html",
    iconfont: "&#xe62d;",
  },
  {
    group: 1,
    cnName: "视频通话",
    enName: "Video Call",
    description: "C++ API for All Platforms",
    product: "Video",
    platform: "Windows",
    category: "cpp",
    url: "index.html",
    iconfont: "&#xe62d;",
  },
  {
    group: 1,
    cnName: "视频通话",
    enName: "Video Call",
    description: "Web SDK API (3.x)",
    product: "Video",
    platform: "Web",
    category: "web",
    url: "index.html",
    iconfont: "&#xe62d;",
  },
  {
    group: 1,
    cnName: "视频通话",
    enName: "Video Call",
    description: "Web SDK API (4.x)",
    product: "Video",
    platform: "Web",
    category: "web_ng",
    url: "index.html",
    iconfont: "&#xe62d;",
  },
  {
    group: 1,
    cnName: "视频通话",
    enName: "Video Call",
    description: "小程序 SDK API",
    product: "Video",
    platform: "微信小程序",
    category: "wechat",
    url: "index.html",
    iconfont: "&#xe62d;",
    lang: ["cn"],
  },
  {
    group: 1,
    cnName: "视频通话",
    enName: "Video Call",
    description: "Electron SDK API",
    product: "Video",
    platform: "Electron",
    category: "electron",
    url: "index.html",
    iconfont: "&#xe62d;",
  },
  {
    group: 1,
    cnName: "视频通话",
    enName: "Video Call",
    description: "Unity SDK API",
    product: "Video",
    platform: "Unity",
    category: "unity",
    url: "index.html",
    iconfont: "&#xe62d;",
  },
  {
    group: 1,
    cnName: "视频通话",
    enName: "Video Call",
    description: "React Native SDK API",
    product: "Video",
    platform: "React Native",
    category: "react_native",
    url: "index.html",
    iconfont: "&#xe62d;",
  },
  {
    group: 1,
    cnName: "视频通话",
    enName: "Video Call",
    description: "Flutter SDK API",
    product: "Video",
    platform: "Flutter",
    category: "flutter",
    url: "index.html",
    iconfont: "&#xe62d;",
  },
  {
    group: 1,
    cnName: "视频通话",
    enName: "Video Call",
    description: "Cocos Creator SDK API",
    product: "Video",
    platform: "Cocos Creator",
    category: "cocos_creator",
    url: "index.html",
    iconfont: "&#xe62d;",
  },
  {
    group: 1,
    cnName: "视频通话",
    enName: "Video Call",
    description: "Cocos2d-x SDK API",
    product: "Video",
    platform: "Cocos2d-x",
    category: "cpp",
    url: "index.html",
    iconfont: "&#xe62d;",
  },
  {
    group: 2,
    cnName: "互动直播",
    enName: "Interactive Live Streaming",
    description: "Android SDK API",
    product: "Interactive Broadcast",
    platform: "Android",
    category: "java",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 5,
    cnName: "媒体播放器组件",
    enName: "MediaPlayer Kit",
    description: "Android SDK API",
    product: "Interactive Broadcast",
    platform: "Android",
    category: "mediaplayer_java",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 6,
    cnName: "推流组件",
    enName: "Streaming Kit",
    description: "Android SDK API",
    product: "Interactive Broadcast",
    platform: "Android",
    category: "rsk_java",
    url: "index.html",
    iconfont: "&#xe631;",
    lang: ["cn"],
  },
  {
    group: 2,
    cnName: "互动直播",
    enName: "Interactive Live Streaming",
    description: "iOS SDK API",
    product: "Interactive Broadcast",
    platform: "iOS",
    category: "oc",
    url: "docs/headers/Agora-Objective-C-API-Overview.html",
    iconfont: "&#xe631;",
  },
  {
    group: 5,
    cnName: "媒体播放器组件",
    enName: "MediaPlayer Kit",
    description: "iOS SDK API",
    product: "Interactive Broadcast",
    platform: "iOS",
    category: "mediaplayer_oc",
    url: "docs/headers/MediaPlayer-Kit-Objective-C-API-Overview.html",
    iconfont: "&#xe631;",
  },
  {
    group: 6,
    cnName: "推流组件",
    enName: "Streaming Kit",
    description: "iOS SDK API",
    product: "Interactive Broadcast",
    platform: "iOS",
    category: "rsk_oc",
    url: "docs/headers/RTMP-Streaming-Kit-Objective-C-API-Overview.html",
    iconfont: "&#xe631;",
    lang: ["cn"],
  },
  {
    group: 2,
    cnName: "互动直播",
    enName: "Interactive Live Streaming",
    description: "macOS SDK API",
    product: "Interactive Broadcast",
    platform: "macOS",
    category: "oc",
    url: "docs/headers/Agora-Objective-C-API-Overview.html",
    iconfont: "&#xe631;",
  },
  {
    group: 5,
    cnName: "媒体播放器组件",
    enName: "MediaPlayer Kit",
    description: "macOS SDK API",
    product: "Interactive Broadcast",
    platform: "macOS",
    category: "mediaplayer_oc",
    url: "docs/headers/MediaPlayer-Kit-Objective-C-API-Overview.html",
    iconfont: "&#xe631;",
  },
  {
    group: 2,
    cnName: "互动直播",
    enName: "Interactive Live Streaming",
    description: "C++ API for All Platforms",
    product: "Interactive Broadcast",
    platform: "Windows",
    category: "cpp",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 5,
    cnName: "媒体播放器组件",
    enName: "MediaPlayer Kit",
    description: "C++ API for All Platforms",
    product: "Interactive Broadcast",
    platform: "Windows",
    category: "mediaplayer_cpp",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 2,
    cnName: "互动直播",
    enName: "Interactive Live Streaming",
    description: "Web SDK API (3.x)",
    product: "Interactive Broadcast",
    platform: "Web",
    category: "web",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 2,
    cnName: "互动直播",
    enName: "Interactive Live Streaming",
    description: "Web SDK API (4.x)",
    product: "Interactive Broadcast",
    platform: "Web",
    category: "web_ng",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 2,
    cnName: "互动直播",
    enName: "Interactive Live Streaming",
    description: "小程序 SDK API",
    product: "Interactive Broadcast",
    platform: "微信小程序",
    category: "wechat",
    url: "index.html",
    iconfont: "&#xe631;",
    lang: ["cn"],
  },
  {
    group: 2,
    cnName: "互动直播",
    enName: "Interactive Live Streaming",
    description: "Electron SDK API",
    product: "Interactive Broadcast",
    platform: "Electron",
    category: "electron",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 2,
    cnName: "互动直播",
    enName: "Interactive Live Streaming",
    description: "Unity SDK API",
    product: "Interactive Broadcast",
    platform: "Unity",
    category: "unity",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 2,
    cnName: "互动直播",
    enName: "Interactive Live Streaming",
    description: "React Native SDK API",
    product: "Interactive Broadcast",
    platform: "React Native",
    category: "react_native",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 2,
    cnName: "互动直播",
    enName: "Interactive Live Streaming",
    description: "Flutter SDK API",
    product: "Interactive Broadcast",
    platform: "Flutter",
    category: "flutter",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 2,
    cnName: "互动直播",
    enName: "Interactive Live Streaming",
    description: "Cocos Creator SDK API",
    product: "Interactive Broadcast",
    platform: "Cocos Creator",
    category: "cocos_creator",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 2,
    cnName: "互动直播",
    enName: "Interactive Live Streaming",
    description: "Cocos2d-x SDK API",
    product: "Interactive Broadcast",
    platform: "Cocos2d-x",
    category: "cpp",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 8,
    cnName: "本地服务端录制",
    enName: "On-premise Recording",
    description: "C++ API for Linux",
    product: "Recording",
    platform: "Linux",
    category: "recording_cpp",
    url: "index.html",
    iconfont: "&#xe62a;",
  },
  {
    group: 8,
    cnName: "本地服务端录制",
    enName: "On-premise Recording",
    description: "Java API for Linux",
    product: "Recording",
    platform: "Linux",
    category: "recording_java",
    url: "index.html",
    iconfont: "&#xe62a;",
  },
  {
    group: 9,
    cnName: "实时消息",
    enName: "Real-time Messaging",
    description: "Android SDK API",
    product: "Real-time-Messaging",
    platform: "Android",
    category: "RTM_java",
    url: "index.html",
    iconfont: "&#xe656;",
  },
  {
    group: 9,
    cnName: "实时消息",
    enName: "Real-time Messaging",
    description: "iOS SDK API",
    product: "Real-time-Messaging",
    platform: "iOS",
    category: "RTM_oc",
    url: "docs/API-Overview.html",
    iconfont: "&#xe656;",
  },
  {
    group: 9,
    cnName: "实时消息",
    enName: "Real-time Messaging",
    description: "macOS SDK API",
    product: "Real-time-Messaging",
    platform: "macOS",
    category: "RTM_oc",
    url: "docs/API-Overview.html",
    iconfont: "&#xe656;",
  },
  {
    group: 9,
    cnName: "实时消息",
    enName: "Real-time Messaging",
    description: "C++ API for Windows",
    product: "Real-time-Messaging",
    platform: "Windows",
    category: "RTM_cpp",
    url: "index.html",
    iconfont: "&#xe656;",
  },
  {
    group: 9,
    cnName: "实时消息",
    enName: "Real-time Messaging",
    description: "Web SDK API",
    product: "Real-time-Messaging",
    platform: "Web",
    category: "RTM_web",
    url: "index.html",
    iconfont: "&#xe656;",
  },
  {
    group: 9,
    cnName: "实时消息",
    enName: "Real-time Messaging",
    description: "小程序 SDK API",
    product: "Real-time-Messaging",
    platform: "微信小程序",
    category: "RTM_wechat",
    url: "index.html",
    iconfont: "&#xe656;",
    lang: ["cn"],
  },
  {
    group: 9,
    cnName: "实时消息",
    enName: "Real-time Messaging",
    description: "C++ API for Linux",
    product: "Real-time-Messaging",
    platform: "Linux",
    category: "RTM_cpp",
    url: "index.html",
    iconfont: "&#xe656;",
  },
  {
    group: 9,
    cnName: "实时消息",
    enName: "Real-time Messaging",
    description: "Java API for Linux",
    product: "Real-time-Messaging",
    platform: "Linux",
    category: "RTM_java_linux",
    url: "index.html",
    iconfont: "&#xe656;",
  },
  {
    group: 10,
    cnName: "事件与历史消息查询",
    enName: "User and Channel Events",
    description: "RESTful API",
    product: "Real-time-Messaging",
    platform: "RESTful",
    category: "markdown",
    url: "Real-time-Messaging/rtm_get_event?platform=All%20Platforms",
    iconfont: "&#xe656;",
  },
  {
    group: 11,
    cnName: "消息发送",
    enName: "User and Channel Events",
    description: "RESTful API",
    product: "Real-time-Messaging",
    platform: "RESTful",
    category: "markdown",
    url: "Real-time-Messaging/messaging_restful?platform=All%20Platforms",
    iconfont: "&#xe656;",
    lang: ["cn"],
  },
  {
    group: 12,
    cnName: "实时码流加速",
    enName: "RTSA",
    description: "Android SDK API",
    product: "RTSA",
    platform: "Android",
    category: "rtsa_java",
    url: "index.html",
    iconfont: "&#xe627;",
    lang: ["cn"],
  },
  {
    group: 12,
    cnName: "实时码流加速",
    enName: "RTSA",
    description: "iOS SDK API",
    product: "RTSA",
    platform: "iOS",
    category: "rtsa_oc",
    url: "docs/mainpage.html",
    iconfont: "&#xe627;",
    lang: ["cn"],
  },
  {
    group: 12,
    cnName: "实时码流加速",
    enName: "RTSA",
    description: "macOS SDK API",
    product: "RTSA",
    platform: "macOS",
    category: "rtsa_oc",
    url: "docs/mainpage.html",
    iconfont: "&#xe627;",
    lang: ["cn"],
  },
  {
    group: 12,
    cnName: "实时码流加速",
    enName: "RTSA",
    description: "C API for Windows",
    product: "RTSA",
    platform: "Windows",
    category: "rtsa_c",
    url: "index.html",
    iconfont: "&#xe627;",
    lang: ["cn"],
  },
  {
    group: 12,
    cnName: "实时码流加速",
    enName: "RTSA",
    description: "C API for Linux",
    product: "RTSA",
    platform: "Linux",
    category: "rtsa_c",
    url: "index.html",
    iconfont: "&#xe627;",
    lang: ["cn"],
  },
  {
    group: 7,
    cnName: "云端录制",
    enName: "Cloud Recording",
    description: "RESTful API",
    product: "cloud-recording",
    platform: "RESTful",
    category: "markdown",
    url: "cloud-recording/cloud_recording_api_rest?platform=RESTful",
    iconfont: "&#xe62f;",
  },
  {
    group: 15,
    cnName: "阿里智能语音审核",
    enName: "阿里智能语音审核",
    description: "RESTful API",
    product: "Aliyun Audio Moderation",
    platform: "RESTful",
    category: "markdown",
    url: "Aliyun%20Audio%20Moderation/restful_api_ali_audio?platform=RESTful",
    iconfont: "&#xe663;",
    lang: ["cn"],
  },
  {
    group: 16,
    cnName: "金山智能语音审核",
    enName: "金山智能语音审核",
    description: "RESTful API",
    product: "Kingsoft Audio Moderation",
    platform: "RESTful",
    category: "markdown",
    url:
      "Kingsoft%20Audio%20Moderation/restful_api_kingsoft_audio?platform=RESTful",
    iconfont: "&#xe664;",
    lang: ["cn"],
  },
  {
    group: 14,
    cnName: "水晶球",
    enName: "Agora Analytics",
    description: "RESTful API",
    product: "Agora Analytics",
    platform: "RESTful",
    category: "markdown",
    url: "Agora%20Platform/aa_api?platform=All%20Platforms",
    iconfont: "&#xe623;",
  },
  {
    group: 3,
    cnName: "极速直播",
    enName: "Interactive Live Streaming",
    description: "Android SDK API",
    product: "live-streaming",
    platform: "Android",
    category: "java",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  // {
  //  group: 5,
  //   cnName: "媒体播放器组件",
  //   enName: "MediaPlayer Kit",
  //   description: "MediaPlayer Kit Java API Reference",
  //   product: "live-streaming",
  //   platform: "Android",
  //   category: "mediaplayer_java",
  //   url: "index.html",
  //   iconfont: "&#xe631;",
  // },
  // {
  //  group: 6,
  //   cnName: "推流组件",
  //   enName: "Streaming Kit",
  //   description: "Streaming Kit Java API Reference",
  //   product: "live-streaming",
  //   platform: "Android",
  //   category: "rsk_java",
  //   url: "index.html",
  //   iconfont: "&#xe631;",
  //   lang: ["cn"],
  // },
  {
    group: 3,
    cnName: "极速直播",
    enName: "Interactive Live Streaming",
    description: "iOS SDK API",
    product: "live-streaming",
    platform: "iOS",
    category: "oc",
    url: "docs/headers/Agora-Objective-C-API-Overview.html",
    iconfont: "&#xe631;",
  },
  // {
  //  group: 5,
  //   cnName: "媒体播放器组件",
  //   enName: "MediaPlayer Kit",
  //   description: "MediaPlayer Kit Objective-C API Reference",
  //   product: "live-streaming",
  //   platform: "iOS",
  //   category: "mediaplayer_oc",
  //   url: "docs/headers/MediaPlayer-Kit-Objective-C-API-Overview.html",
  //   iconfont: "&#xe631;",
  // },
  // {
  //  group: 6,
  //   cnName: "推流组件",
  //   enName: "Streaming Kit",
  //   description: "Streaming Kit Objective-C API Reference",
  //   product: "live-streaming",
  //   platform: "iOS",
  //   category: "rsk_oc",
  //   url: "docs/headers/RTMP-Streaming-Kit-Objective-C-API-Overview.html",
  //   iconfont: "&#xe631;",
  //   lang: ["cn"],
  // },
  {
    group: 3,
    cnName: "极速直播",
    enName: "Interactive Live Streaming",
    description: "macOS SDK API",
    product: "live-streaming",
    platform: "macOS",
    category: "oc",
    url: "docs/headers/Agora-Objective-C-API-Overview.html",
    iconfont: "&#xe631;",
  },
  // {
  //  group: 5,
  //   cnName: "媒体播放器组件",
  //   enName: "MediaPlayer Kit",
  //   description: "MediaPlayer Kit Objective-C API Reference",
  //   product: "live-streaming",
  //   platform: "macOS",
  //   category: "mediaplayer_oc",
  //   url: "docs/headers/MediaPlayer-Kit-Objective-C-API-Overview.html",
  //   iconfont: "&#xe631;",
  // },
  {
    group: 3,
    cnName: "极速直播",
    enName: "Interactive Live Streaming",
    description: "C++ API for All Platforms",
    product: "live-streaming",
    platform: "Windows",
    category: "cpp",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  // {
  //  group: 5,
  //   cnName: "媒体播放器组件",
  //   enName: "MediaPlayer Kit",
  //   description: "MediaPlayer Kit C++ API Reference",
  //   product: "live-streaming",
  //   platform: "Windows",
  //   category: "mediaplayer_cpp",
  //   url: "index.html",
  //   iconfont: "&#xe631;",
  // },
  {
    group: 3,
    cnName: "极速直播",
    enName: "Interactive Live Streaming",
    description: "Web SDK API (3.x)",
    product: "live-streaming",
    platform: "Web",
    category: "web",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 3,
    cnName: "极速直播",
    enName: "Interactive Live Streaming",
    description: "Web SDK API (4.x)",
    product: "live-streaming",
    platform: "Web",
    category: "web_ng",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 3,
    cnName: "极速直播",
    enName: "Interactive Live Streaming",
    description: "小程序 SDK API",
    product: "live-streaming",
    platform: "微信小程序",
    category: "wechat",
    url: "index.html",
    iconfont: "&#xe631;",
    lang: ["cn"],
  },
  {
    group: 3,
    cnName: "极速直播",
    enName: "Interactive Live Streaming",
    description: "Electron SDK API",
    product: "live-streaming",
    platform: "Electron",
    category: "electron",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 3,
    cnName: "极速直播",
    enName: "Interactive Live Streaming",
    description: "Unity SDK API",
    product: "live-streaming",
    platform: "Unity",
    category: "unity",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 3,
    cnName: "极速直播",
    enName: "Interactive Live Streaming",
    description: "React Native SDK API",
    product: "live-streaming",
    platform: "React Native",
    category: "react_native",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 3,
    cnName: "极速直播",
    enName: "Interactive Live Streaming",
    description: "Flutter SDK API",
    product: "live-streaming",
    platform: "Flutter",
    category: "flutter",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  {
    group: 3,
    cnName: "极速直播",
    enName: "Interactive Live Streaming",
    description: "Cocos Creator SDK API",
    product: "live-streaming",
    platform: "Cocos Creator",
    category: "cocos_creator",
    url: "index.html",
    iconfont: "&#xe631;",
  },
  // {
  //   group: 13,
  //   cnName: "教育云服务",
  //   enName: "教育云服务",
  //   description: "RESTful API",
  //   product: "agora-class",
  //   platform: "Android",
  //   category: "markdown",
  //   url: "agora-class/agora_class_restful_api?platform=Android",
  //   iconfont: "&#xe67c;",
  //   lang: ["cn"],
  // },
  // {
  //   group: 13,
  //   cnName: "教育云服务",
  //   enName: "教育云服务",
  //   description: "RESTful API",
  //   product: "agora-class",
  //   platform: "iOS",
  //   category: "markdown",
  //   url: "agora-class/agora_class_restful_api?platform=iOS",
  //   iconfont: "&#xe67c;",
  //   lang: ["cn"],
  // },
  // {
  //   group: 13,
  //   cnName: "教育云服务",
  //   enName: "教育云服务",
  //   description: "RESTful API",
  //   product: "agora-class",
  //   platform: "Web",
  //   category: "markdown",
  //   url: "agora-class/agora_class_restful_api?platform=Web",
  //   iconfont: "&#xe67c;",
  //   lang: ["cn"],
  // },
  {
    group: 13,
    cnName: "灵动课堂云服务",
    enName: "灵动课堂云服务",
    description: "RESTful API",
    product: "agora-class",
    platform: "RESTful",
    category: "markdown",
    url: "agora-class/agora_class_restful_api?platform=RESTful",
    iconfont: "&#xe67c;",
    lang: ["cn"],
  },
  {
    group: 1,
    cnName: "视频通话",
    enName: "Video Call",
    description: "RESTful API",
    product: "Video",
    platform: "RESTful",
    category: "swagger",
    url: "rtc/restfulapi",
    iconfont: "&#xe62d;",
  },
  {
    group: 2,
    cnName: "互动直播",
    enName: "Interactive Live Streaming",
    description: "RESTful API",
    product: "Interactive Broadcast",
    platform: "RESTful",
    category: "swagger",
    url: "rtc/restfulapi",
    iconfont: "&#xe631;",
  },
  {
    group: 3,
    cnName: "极速直播",
    enName: "Interactive Live Streaming",
    description: "RESTful API",
    product: "live-streaming",
    platform: "RESTful",
    category: "swagger",
    url: "rtc/restfulapi",
    iconfont: "&#xe631;",
  },
];
