const product2PlatformMap = {
  Voice: [
    "All Platforms",
    "Android",
    "iOS",
    "macOS",
    "Web",
    "微信小程序",
    "Windows",
    "RESTful",
    "Electron",
    "Unity",
    "Flutter",
    "React Native",
    "Cocos Creator",
  ],
  Video: [
    "All Platforms",
    "Android",
    "iOS",
    "macOS",
    "Web",
    "微信小程序",
    "Windows",
    "RESTful",
    "Electron",
    "Unity",
    "Flutter",
    "React Native",
    "Cocos Creator",
  ],
  "Interactive Streaming": [
    "All Platforms",
    "Android",
    "iOS",
    "macOS",
    "Web",
    "微信小程序",
    "Windows",
    "RESTful",
    "Electron",
    "Unity",
    "Flutter",
    "React Native",
    "Cocos Creator",
  ], // 互动直播
  极速直播: [
    "All Platforms",
    "Android",
    "iOS",
    "macOS",
    "Web",
    "微信小程序",
    "Windows",
    "RESTful",
    "Electron",
    "Unity",
    "Flutter",
    "React Native",
    "Cocos Creator",
  ],
  "cloud-recording": ["All Platforms", "RESTful"], // 云端录制
  // "Audio Broadcast": [],
  // "Interactive Gaming": [],
  Recording: ["All Platforms", "Linux"], // 本地服务端录制
  "Real-time-Messaging": [
    "All Platforms",
    "Android",
    "iOS",
    "macOS",
    "Web",
    "微信小程序",
    "Windows",
    "Linux",
    "RESTful",
  ],
  RTSA: ["All Platforms", "Android", "iOS", "macOS", "Windows", "Linux"],
  "Agora Analytics": [
    "All Platforms",
    "Android",
    "iOS",
    "macOS",
    "Web",
    "微信小程序",
    "Windows",
    "Linux",
    "RESTful",
    "Electron",
    "Unity",
    "Flutter",
    "React Native",
    "Cocos Creator",
  ], // 水晶球
  "Agora Platform": [
    "All Platforms",
    "Android",
    "iOS",
    "macOS",
    "Web",
    "微信小程序",
    "Windows",
    "Linux",
    "RESTful",
    "Electron",
    "Unity",
    "Flutter",
    "React Native",
    "Cocos Creator",
  ],
  "Aliyun Audio Moderation": ["All Platforms", "RESTful"],
  "Kingsoft Audio Moderation": ["All Platforms", "RESTful"],
  "Volcengine AI Vision": ["All Platforms", "Android", "iOS"],
  "AI Interactive Classroom": [
    "All Platforms",
    "Android",
    "iOS",
    "macOS",
    "Web",
    "Windows",
  ],
  "One-to-one Classroom": ["All Platforms", "Android", "iOS", "Web", "RESTful"],
  "Small Classroom": ["All Platforms", "Android", "iOS", "Web", "RESTful"],
  "Lecture Hall": ["All Platforms", "Android", "iOS", "Web", "RESTful"],
  "Breakout Classroom": ["All Platforms", "Android", "iOS", "Web", "RESTful"],
  "Single Host": ["All Platforms", "Android", "iOS"],
  "Multiple Hosts": ["All Platforms", "Android", "iOS"],
  "PK Host": ["All Platforms", "Android", "iOS"],
  "Virtual Host": ["All Platforms", "Android", "iOS"],
  "Live-stream Shopping": ["All Platforms", "Android", "iOS"],
};
